### ISSUE TITLE
What are the current plans for this project?

### ISSUE THREAD

**Issue by xuehuihui** [virtio-win/attestation_signing#1]

**Comment by vrozenfe** [comment]
@xuehuihui 
What exactly do you want to know?
Win10(+) drivers available at https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.229-1/ are attestation signed.

Vadim.

**Comment by YanVugenfirer** [comment]
@xuehuihui This is a placeholder for the code to automate attestation signing.

Best regards,
Yan.
